metadata:
  general_description: Unimputed SNP variants for 22626 BRIDGE project panel genotypes with reference to Morex V3
  vcf_doi: 
  vcf_reference_genome_doi: http://doi.org/10.5447/ipk/2021/3
  gff3_doi: http://doi.org/10.5447/ipk/2021/3

datadir: C:/Users/Boss/Desktop/vcf-to-api/data/

variants:
  zarr_dir: SNP_matrix_WGS_300_samples_subset_500k_first_rows.zarr
  sample_id_mapping_filename:

gff3:
  reference_seq: GRCh38_latest_genomic.fna
  vcf_file: ALL.shapeit2_integrated_v1a.GRCh38.20181129.phased.vcf.gz
  additional_attributes_keys:  biotype,gene_id
  filename: Barley_Morex_V2_gene_annotation_PGSB.all.gff3
  key_confidence: primary_confidence_class
  key_ontology: Ontology_term
  feature_type_with_description: mRNA
  count_exon_variants: false
  key_ontology: Ontology_term
  feature_type_with_description: gene
  main_feature_types_for_genes_track:
    - gene
    - pseudogene
    - ncRNA_gene
  count_exon_variants: false
  external_link_ontology_term: https://www.ebi.ac.uk/QuickGO/term/{ID}
  external_links:
    - feature_type: mRNA
      feature_attribute: ID
      url: https://apex.ipk-gatersleben.de/apex/f?p=284:58:::::P58_GENE_NAME:{FEATURE_ID}
      linktext: Open this gene in BARLEX


chromosome_labels:
  1: 1H
  2: 2H
  3: 3H
  4: 4H
  5: 5H
  6: 6H
  7: 7H
  0: Un


gff3_chromosome_labels:
  1: chr1H
  2: chr2H
  3: chr3H
  4: chr4H
  5: chr5H
  6: chr6H
  7: chr7H
  0: chrUn


centromeres_positions:
  1: 205502676
  2: 305853815
  3: 271947776
  4: 282386439
  5: 205989812
  6: 260041240
  7: 328847863
  0: 0


blast:
  active: false
  galaxy_server_url: 
  galaxy_user: 
  galaxy_pass: 
  galaxy_tool_id: 
  blast_database: 
  blast_type: megablast
  blast_result_to_vcf_chromosome_mapping:
    chr1H: 1
    chr2H: 2
    chr3H: 3
    chr4H: 4
    chr5H: 5
    chr6H: 6
    chr7H: 7
    chrUn: 0